Add --env-file for defaults for env object
Viasat/dctest pull request #20
Opened 2024-11-07 20:16 UTC by kanaka

Use dotenv npm module for parsing environment files to populate the base env object/map.

2024-11-15 21:03 UTC, jonsmock requested changes
Following up on the actual PR with out-of-band discussion, looks good to me with the agreed upon changes:

- rename flag to `--environ-file-unsafe` (future can add `--environ-file`) due to node versions prior to node 22 consuming the `--env-file` https://github.com/babashka/nbb/issues/371
- addition of at least one test that exercises it in GHA somehow

2024-11-20 00:02 UTC, jonsmock commented on src/dctest/util.cljs
> +    [viasat.util :refer [Eprintln fatal read-file exec-promise]]
not important: probably don't need exec-promise anymore :-)

2024-11-20 00:03 UTC, jonsmock approved these changes
Yay! Looks awesome!

2024-11-20 15:04 UTC, kanaka commented on src/dctest/util.cljs
> +    [viasat.util :refer [Eprintln fatal read-file exec-promise]]
I fixed that, thanks.

2024-11-20 15:05 UTC, merged